baseURL = 'https://brettstark.com'
languageCode = 'en-us'
title = 'Brett Stark'
theme = 'hugo-papermod'

[params]
  description = 'Technology, Space, Travel, and Photography'
  author = 'Brett Stark'
  tagline = 'Aussie in Chicago'

  # SEO settings
  env = 'production'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "Welcome to Brett Stark's Blog"
  Content = "Technology, Space, Travel, and Photography from an Aussie in Chicago"


[params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/safari-pinned-tab.svg"
  
[menu]
  [[menu.main]]
    name = 'Blog'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    name = 'Contact'  
    url = '/contact/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true