baseURL = 'https://brettstark.com'
languageCode = 'en-us'
title = 'Brett Stark'
theme = 'hugo-papermod'

[params]
  description = 'Technology, Space, Travel, and Photography'
  author = 'Brett Stark'
  tagline = 'Aussie in Chicago'

  # SEO settings
  env = 'production'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShareButtons = ["x", "linkedin", "facebook", "instagram"]
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "Welcome to Brett Stark's Blog"
  Content = "Technology, Space, Travel, and Photography from an Aussie in Chicago"


  images = ["/brand/profile-picture.jpg"]

[params.assets]
  favicon = "/brand/profile-picture.jpg"
  favicon16x16 = "/brand/profile-picture.jpg"
  favicon32x32 = "/brand/profile-picture.jpg"
  apple_touch_icon = "/brand/profile-picture.jpg"
  safari_pinned_tab = "/brand/profile-picture.jpg"
  
[menu]
  [[menu.main]]
    name = 'Blog'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    name = 'Contact'  
    url = '/contact/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Image processing configuration
[imaging]
  # Default JPEG quality (0-100, higher is better quality but larger file size)
  quality = 82
  # Resample filter used for resizing (Box, NearestNeighbor, Linear, Gaussian, Lanczos)
  resampleFilter = "Lanczos"
  # Anchor position for cropping (Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight)
  anchor = "Smart"

  # Background color for transparent images when converting to JPEG
  bgColor = "#ffffff"